name:  examen-workflow
on:
  push:
    branches: [ nueva-caracteristica ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar el codigo
      uses: actions/checkout@v4
    - name: Configurar el entorno Python
      uses: actions/setup-python@v5
    - name: instalar pytest
      run: pip install pytest
    - name: Probar codigo
      run: pytest test.py
    - name: Construir la imagen
      uses: docker/build-push-action@v6
      with:
        file: ej1-Dockerfile
